---
- name: Download Ubuntu 20.04 (Focal Fossa) LXC image
  ansible.builtin.command:
    argv:
      - pveam
      - download
      - local
      - ubuntu-20.04-standard_20.04-1_amd64.tar.gz

- name: Download Ubuntu 18.04 (Bionic Beaver) LXC image
  ansible.builtin.command:
    argv:
      - pveam
      - download
      - local
      - ubuntu-18.04-standard_18.04.1-1_amd64.tar.gz

- name: Change ownership and set correct file/directory permissions
  include_tasks: setup_files.yml
  loop:
    - /mnt/storage/media/movies
    - /mnt/storage/media/music
    - /mnt/storage/media/tv
    - /mnt/storage/downloads/usenet
    - /mnt/storage/downloads/torrents

- name: Recursively change ownership of scratch share directory
  ansible.builtin.file:
    path: /mnt/storage/shares/scratch
    state: directory
    recurse: true
    owner: "100000"
    group: "100118"

- name: Recursively change ownership of videos share directory
  ansible.builtin.file:
    path: /mnt/storage/media/videos
    state: directory
    recurse: true
    owner: "101000"
    group: "100118"

- name: Recursively change ownership of brian share directory
  ansible.builtin.file:
    path: /mnt/storage/shares/brian
    state: directory
    recurse: true
    owner: "101000"
    group: "100118"

- name: Recursively change ownership of charlene share directory
  ansible.builtin.file:
    path: /mnt/storage/shares/charlene
    state: directory
    recurse: true
    owner: "101001"
    group: "100118"

- name: Recursively change ownership of Tdarr config directory
  ansible.builtin.file:
    path: /mnt/storage/appdata/tdarr/config
    state: directory
    recurse: true
    owner: "101000"
    group: "101000"

- name: Recursively change ownership of Beets config directory
  ansible.builtin.file:
    path: /mnt/storage/appdata/beets/config
    state: directory
    recurse: true
    owner: "100000"
    group: "100000"

- name: Recursively change ownership of Duck DNS config directory
  ansible.builtin.file:
    path: /mnt/storage/appdata/duckdns/config
    state: directory
    recurse: true
    owner: "100000"
    group: "100000"

- name: Recursively change ownership of Traefik config directory
  ansible.builtin.file:
    path: /mnt/storage/appdata/traefik/config
    state: directory
    recurse: true
    owner: "101000"
    group: "101000"

- name: Recursively change ownership of Syncthing config directory
  ansible.builtin.file:
    path: /mnt/storage/appdata/syncthing
    state: directory
    recurse: true
    owner: "101000"
    group: "101000"

- name: Recursively change ownership of Lidarr config directory
  ansible.builtin.file:
    path: /mnt/storage/appdata/lidarr
    state: directory
    recurse: true
    owner: "101000"
    group: "101000"
