---
- import_playbook: ./playbooks/bazarr.yml
- import_playbook: ./playbooks/immich.yml
- import_playbook: ./playbooks/jellyfin.yml
- import_playbook: ./playbooks/network.yml
- import_playbook: ./playbooks/pi-hole.yml
- import_playbook: ./playbooks/prowlarr.yml
- import_playbook: ./playbooks/qbittorrent.yml
- import_playbook: ./playbooks/radarr.yml
- import_playbook: ./playbooks/samba.yml
- import_playbook: ./playbooks/sonarr.yml
- import_playbook: ./playbooks/syncthing.yml
- import_playbook: ./playbooks/traefik.yml
- import_playbook: ./playbooks/unifi.yml
